<?php
/**
 * CorrelationMessageDto
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  StrehleDe\CamundaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace StrehleDe\CamundaClient\Model;

use \ArrayAccess;
use \StrehleDe\CamundaClient\ObjectSerializer;

/**
 * CorrelationMessageDto Class Doc Comment
 *
 * @category Class
 * @package  StrehleDe\CamundaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CorrelationMessageDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CorrelationMessageDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'message_name' => 'string',
        'business_key' => 'string',
        'tenant_id' => 'string',
        'without_tenant_id' => 'bool',
        'process_instance_id' => 'string',
        'correlation_keys' => 'map[string,\StrehleDe\CamundaClient\Model\VariableValueDto]',
        'local_correlation_keys' => 'map[string,\StrehleDe\CamundaClient\Model\VariableValueDto]',
        'process_variables' => 'map[string,\StrehleDe\CamundaClient\Model\VariableValueDto]',
        'process_variables_local' => 'map[string,\StrehleDe\CamundaClient\Model\VariableValueDto]',
        'all' => 'bool',
        'result_enabled' => 'bool',
        'variables_in_result_enabled' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'message_name' => null,
        'business_key' => null,
        'tenant_id' => null,
        'without_tenant_id' => null,
        'process_instance_id' => null,
        'correlation_keys' => null,
        'local_correlation_keys' => null,
        'process_variables' => null,
        'process_variables_local' => null,
        'all' => null,
        'result_enabled' => null,
        'variables_in_result_enabled' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'message_name' => 'messageName',
        'business_key' => 'businessKey',
        'tenant_id' => 'tenantId',
        'without_tenant_id' => 'withoutTenantId',
        'process_instance_id' => 'processInstanceId',
        'correlation_keys' => 'correlationKeys',
        'local_correlation_keys' => 'localCorrelationKeys',
        'process_variables' => 'processVariables',
        'process_variables_local' => 'processVariablesLocal',
        'all' => 'all',
        'result_enabled' => 'resultEnabled',
        'variables_in_result_enabled' => 'variablesInResultEnabled'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'message_name' => 'setMessageName',
        'business_key' => 'setBusinessKey',
        'tenant_id' => 'setTenantId',
        'without_tenant_id' => 'setWithoutTenantId',
        'process_instance_id' => 'setProcessInstanceId',
        'correlation_keys' => 'setCorrelationKeys',
        'local_correlation_keys' => 'setLocalCorrelationKeys',
        'process_variables' => 'setProcessVariables',
        'process_variables_local' => 'setProcessVariablesLocal',
        'all' => 'setAll',
        'result_enabled' => 'setResultEnabled',
        'variables_in_result_enabled' => 'setVariablesInResultEnabled'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'message_name' => 'getMessageName',
        'business_key' => 'getBusinessKey',
        'tenant_id' => 'getTenantId',
        'without_tenant_id' => 'getWithoutTenantId',
        'process_instance_id' => 'getProcessInstanceId',
        'correlation_keys' => 'getCorrelationKeys',
        'local_correlation_keys' => 'getLocalCorrelationKeys',
        'process_variables' => 'getProcessVariables',
        'process_variables_local' => 'getProcessVariablesLocal',
        'all' => 'getAll',
        'result_enabled' => 'getResultEnabled',
        'variables_in_result_enabled' => 'getVariablesInResultEnabled'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['message_name'] = isset($data['message_name']) ? $data['message_name'] : null;
        $this->container['business_key'] = isset($data['business_key']) ? $data['business_key'] : null;
        $this->container['tenant_id'] = isset($data['tenant_id']) ? $data['tenant_id'] : null;
        $this->container['without_tenant_id'] = isset($data['without_tenant_id']) ? $data['without_tenant_id'] : false;
        $this->container['process_instance_id'] = isset($data['process_instance_id']) ? $data['process_instance_id'] : null;
        $this->container['correlation_keys'] = isset($data['correlation_keys']) ? $data['correlation_keys'] : null;
        $this->container['local_correlation_keys'] = isset($data['local_correlation_keys']) ? $data['local_correlation_keys'] : null;
        $this->container['process_variables'] = isset($data['process_variables']) ? $data['process_variables'] : null;
        $this->container['process_variables_local'] = isset($data['process_variables_local']) ? $data['process_variables_local'] : null;
        $this->container['all'] = isset($data['all']) ? $data['all'] : false;
        $this->container['result_enabled'] = isset($data['result_enabled']) ? $data['result_enabled'] : false;
        $this->container['variables_in_result_enabled'] = isset($data['variables_in_result_enabled']) ? $data['variables_in_result_enabled'] : false;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets message_name
     *
     * @return string|null
     */
    public function getMessageName()
    {
        return $this->container['message_name'];
    }

    /**
     * Sets message_name
     *
     * @param string|null $message_name The name of the message to deliver.
     *
     * @return $this
     */
    public function setMessageName($message_name)
    {
        $this->container['message_name'] = $message_name;

        return $this;
    }

    /**
     * Gets business_key
     *
     * @return string|null
     */
    public function getBusinessKey()
    {
        return $this->container['business_key'];
    }

    /**
     * Sets business_key
     *
     * @param string|null $business_key Used for correlation of process instances that wait for incoming messages. Will only correlate to executions that belong to a process instance with the provided business key.
     *
     * @return $this
     */
    public function setBusinessKey($business_key)
    {
        $this->container['business_key'] = $business_key;

        return $this;
    }

    /**
     * Gets tenant_id
     *
     * @return string|null
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param string|null $tenant_id Used to correlate the message for a tenant with the given id. Will only correlate to executions and process definitions which belong to the tenant. Must not be supplied in conjunction with a `withoutTenantId`.
     *
     * @return $this
     */
    public function setTenantId($tenant_id)
    {
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets without_tenant_id
     *
     * @return bool|null
     */
    public function getWithoutTenantId()
    {
        return $this->container['without_tenant_id'];
    }

    /**
     * Sets without_tenant_id
     *
     * @param bool|null $without_tenant_id A Boolean value that indicates whether the message should only be correlated to executions and process definitions which belong to no tenant or not. Value may only be `true`, as `false` is the default behavior. Must not be supplied in conjunction with a `tenantId`.
     *
     * @return $this
     */
    public function setWithoutTenantId($without_tenant_id)
    {
        $this->container['without_tenant_id'] = $without_tenant_id;

        return $this;
    }

    /**
     * Gets process_instance_id
     *
     * @return string|null
     */
    public function getProcessInstanceId()
    {
        return $this->container['process_instance_id'];
    }

    /**
     * Sets process_instance_id
     *
     * @param string|null $process_instance_id Used to correlate the message to the process instance with the given id.
     *
     * @return $this
     */
    public function setProcessInstanceId($process_instance_id)
    {
        $this->container['process_instance_id'] = $process_instance_id;

        return $this;
    }

    /**
     * Gets correlation_keys
     *
     * @return map[string,\StrehleDe\CamundaClient\Model\VariableValueDto]|null
     */
    public function getCorrelationKeys()
    {
        return $this->container['correlation_keys'];
    }

    /**
     * Sets correlation_keys
     *
     * @param map[string,\StrehleDe\CamundaClient\Model\VariableValueDto]|null $correlation_keys Used for correlation of process instances that wait for incoming messages. Has to be a JSON object containing key-value pairs that are matched against process instance variables during correlation. Each key is a variable name and each value a JSON variable value object with the following properties.
     *
     * @return $this
     */
    public function setCorrelationKeys($correlation_keys)
    {
        $this->container['correlation_keys'] = $correlation_keys;

        return $this;
    }

    /**
     * Gets local_correlation_keys
     *
     * @return map[string,\StrehleDe\CamundaClient\Model\VariableValueDto]|null
     */
    public function getLocalCorrelationKeys()
    {
        return $this->container['local_correlation_keys'];
    }

    /**
     * Sets local_correlation_keys
     *
     * @param map[string,\StrehleDe\CamundaClient\Model\VariableValueDto]|null $local_correlation_keys Local variables used for correlation of executions (process instances) that wait for incoming messages. Has to be a JSON object containing key-value pairs that are matched against local variables during correlation. Each key is a variable name and each value a JSON variable value object with the following properties.
     *
     * @return $this
     */
    public function setLocalCorrelationKeys($local_correlation_keys)
    {
        $this->container['local_correlation_keys'] = $local_correlation_keys;

        return $this;
    }

    /**
     * Gets process_variables
     *
     * @return map[string,\StrehleDe\CamundaClient\Model\VariableValueDto]|null
     */
    public function getProcessVariables()
    {
        return $this->container['process_variables'];
    }

    /**
     * Sets process_variables
     *
     * @param map[string,\StrehleDe\CamundaClient\Model\VariableValueDto]|null $process_variables A map of variables that is injected into the triggered execution or process instance after the message has been delivered. Each key is a variable name and each value a JSON variable value object with the following properties.
     *
     * @return $this
     */
    public function setProcessVariables($process_variables)
    {
        $this->container['process_variables'] = $process_variables;

        return $this;
    }

    /**
     * Gets process_variables_local
     *
     * @return map[string,\StrehleDe\CamundaClient\Model\VariableValueDto]|null
     */
    public function getProcessVariablesLocal()
    {
        return $this->container['process_variables_local'];
    }

    /**
     * Sets process_variables_local
     *
     * @param map[string,\StrehleDe\CamundaClient\Model\VariableValueDto]|null $process_variables_local A map of local variables that is injected into the triggered execution or process instance after the message has been delivered. Each key is a variable name and each value a JSON variable value object with the following properties.
     *
     * @return $this
     */
    public function setProcessVariablesLocal($process_variables_local)
    {
        $this->container['process_variables_local'] = $process_variables_local;

        return $this;
    }

    /**
     * Gets all
     *
     * @return bool|null
     */
    public function getAll()
    {
        return $this->container['all'];
    }

    /**
     * Sets all
     *
     * @param bool|null $all A Boolean value that indicates whether the message should be correlated to exactly one entity or multiple entities. If the value is set to `false`, the message will be correlated to exactly one entity (execution or process definition). If the value is set to `true`, the message will be correlated to multiple executions and a process definition that can be instantiated by this message in one go.
     *
     * @return $this
     */
    public function setAll($all)
    {
        $this->container['all'] = $all;

        return $this;
    }

    /**
     * Gets result_enabled
     *
     * @return bool|null
     */
    public function getResultEnabled()
    {
        return $this->container['result_enabled'];
    }

    /**
     * Sets result_enabled
     *
     * @param bool|null $result_enabled A Boolean value that indicates whether the result of the correlation should be returned or not. If this property is set to `true`, there will be returned a list of message correlation result objects. Depending on the all property, there will be either one ore more returned results in the list.  The default value is `false`, which means no result will be returned.
     *
     * @return $this
     */
    public function setResultEnabled($result_enabled)
    {
        $this->container['result_enabled'] = $result_enabled;

        return $this;
    }

    /**
     * Gets variables_in_result_enabled
     *
     * @return bool|null
     */
    public function getVariablesInResultEnabled()
    {
        return $this->container['variables_in_result_enabled'];
    }

    /**
     * Sets variables_in_result_enabled
     *
     * @param bool|null $variables_in_result_enabled A Boolean value that indicates whether the result of the correlation should contain process variables or not. The parameter resultEnabled should be set to `true` in order to use this it.  The default value is `false`, which means the variables will not be returned.
     *
     * @return $this
     */
    public function setVariablesInResultEnabled($variables_in_result_enabled)
    {
        $this->container['variables_in_result_enabled'] = $variables_in_result_enabled;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


