<?php
/**
 * FetchExternalTaskTopicDto
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  StrehleDe\CamundaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace StrehleDe\CamundaClient\Model;

use \ArrayAccess;
use \StrehleDe\CamundaClient\ObjectSerializer;

/**
 * FetchExternalTaskTopicDto Class Doc Comment
 *
 * @category Class
 * @package  StrehleDe\CamundaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FetchExternalTaskTopicDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'FetchExternalTaskTopicDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'topic_name' => 'string',
        'lock_duration' => 'int',
        'variables' => 'string[]',
        'local_variables' => 'bool',
        'business_key' => 'string',
        'process_definition_id' => 'string',
        'process_definition_id_in' => 'string[]',
        'process_definition_key' => 'string',
        'process_definition_key_in' => 'string[]',
        'process_definition_version_tag' => 'string',
        'without_tenant_id' => 'bool',
        'tenant_id_in' => 'string[]',
        'process_variables' => 'map[string,object]',
        'deserialize_values' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'topic_name' => null,
        'lock_duration' => 'int64',
        'variables' => null,
        'local_variables' => null,
        'business_key' => null,
        'process_definition_id' => null,
        'process_definition_id_in' => null,
        'process_definition_key' => null,
        'process_definition_key_in' => null,
        'process_definition_version_tag' => null,
        'without_tenant_id' => null,
        'tenant_id_in' => null,
        'process_variables' => null,
        'deserialize_values' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'topic_name' => 'topicName',
        'lock_duration' => 'lockDuration',
        'variables' => 'variables',
        'local_variables' => 'localVariables',
        'business_key' => 'businessKey',
        'process_definition_id' => 'processDefinitionId',
        'process_definition_id_in' => 'processDefinitionIdIn',
        'process_definition_key' => 'processDefinitionKey',
        'process_definition_key_in' => 'processDefinitionKeyIn',
        'process_definition_version_tag' => 'processDefinitionVersionTag',
        'without_tenant_id' => 'withoutTenantId',
        'tenant_id_in' => 'tenantIdIn',
        'process_variables' => 'processVariables',
        'deserialize_values' => 'deserializeValues'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'topic_name' => 'setTopicName',
        'lock_duration' => 'setLockDuration',
        'variables' => 'setVariables',
        'local_variables' => 'setLocalVariables',
        'business_key' => 'setBusinessKey',
        'process_definition_id' => 'setProcessDefinitionId',
        'process_definition_id_in' => 'setProcessDefinitionIdIn',
        'process_definition_key' => 'setProcessDefinitionKey',
        'process_definition_key_in' => 'setProcessDefinitionKeyIn',
        'process_definition_version_tag' => 'setProcessDefinitionVersionTag',
        'without_tenant_id' => 'setWithoutTenantId',
        'tenant_id_in' => 'setTenantIdIn',
        'process_variables' => 'setProcessVariables',
        'deserialize_values' => 'setDeserializeValues'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'topic_name' => 'getTopicName',
        'lock_duration' => 'getLockDuration',
        'variables' => 'getVariables',
        'local_variables' => 'getLocalVariables',
        'business_key' => 'getBusinessKey',
        'process_definition_id' => 'getProcessDefinitionId',
        'process_definition_id_in' => 'getProcessDefinitionIdIn',
        'process_definition_key' => 'getProcessDefinitionKey',
        'process_definition_key_in' => 'getProcessDefinitionKeyIn',
        'process_definition_version_tag' => 'getProcessDefinitionVersionTag',
        'without_tenant_id' => 'getWithoutTenantId',
        'tenant_id_in' => 'getTenantIdIn',
        'process_variables' => 'getProcessVariables',
        'deserialize_values' => 'getDeserializeValues'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['topic_name'] = isset($data['topic_name']) ? $data['topic_name'] : null;
        $this->container['lock_duration'] = isset($data['lock_duration']) ? $data['lock_duration'] : null;
        $this->container['variables'] = isset($data['variables']) ? $data['variables'] : null;
        $this->container['local_variables'] = isset($data['local_variables']) ? $data['local_variables'] : false;
        $this->container['business_key'] = isset($data['business_key']) ? $data['business_key'] : null;
        $this->container['process_definition_id'] = isset($data['process_definition_id']) ? $data['process_definition_id'] : null;
        $this->container['process_definition_id_in'] = isset($data['process_definition_id_in']) ? $data['process_definition_id_in'] : null;
        $this->container['process_definition_key'] = isset($data['process_definition_key']) ? $data['process_definition_key'] : null;
        $this->container['process_definition_key_in'] = isset($data['process_definition_key_in']) ? $data['process_definition_key_in'] : null;
        $this->container['process_definition_version_tag'] = isset($data['process_definition_version_tag']) ? $data['process_definition_version_tag'] : null;
        $this->container['without_tenant_id'] = isset($data['without_tenant_id']) ? $data['without_tenant_id'] : false;
        $this->container['tenant_id_in'] = isset($data['tenant_id_in']) ? $data['tenant_id_in'] : null;
        $this->container['process_variables'] = isset($data['process_variables']) ? $data['process_variables'] : null;
        $this->container['deserialize_values'] = isset($data['deserialize_values']) ? $data['deserialize_values'] : false;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['topic_name'] === null) {
            $invalidProperties[] = "'topic_name' can't be null";
        }
        if ($this->container['lock_duration'] === null) {
            $invalidProperties[] = "'lock_duration' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets topic_name
     *
     * @return string
     */
    public function getTopicName()
    {
        return $this->container['topic_name'];
    }

    /**
     * Sets topic_name
     *
     * @param string $topic_name **Mandatory.** The topic's name.
     *
     * @return $this
     */
    public function setTopicName($topic_name)
    {
        $this->container['topic_name'] = $topic_name;

        return $this;
    }

    /**
     * Gets lock_duration
     *
     * @return int
     */
    public function getLockDuration()
    {
        return $this->container['lock_duration'];
    }

    /**
     * Sets lock_duration
     *
     * @param int $lock_duration **Mandatory.** The duration to lock the external tasks for in milliseconds.
     *
     * @return $this
     */
    public function setLockDuration($lock_duration)
    {
        $this->container['lock_duration'] = $lock_duration;

        return $this;
    }

    /**
     * Gets variables
     *
     * @return string[]|null
     */
    public function getVariables()
    {
        return $this->container['variables'];
    }

    /**
     * Sets variables
     *
     * @param string[]|null $variables A JSON array of `String` values that represent variable names. For each result task belonging to this topic, the given variables are returned as well if they are accessible from the external task's execution. If not provided - all variables will be fetched.
     *
     * @return $this
     */
    public function setVariables($variables)
    {
        $this->container['variables'] = $variables;

        return $this;
    }

    /**
     * Gets local_variables
     *
     * @return bool|null
     */
    public function getLocalVariables()
    {
        return $this->container['local_variables'];
    }

    /**
     * Sets local_variables
     *
     * @param bool|null $local_variables If `true` only local variables will be fetched.
     *
     * @return $this
     */
    public function setLocalVariables($local_variables)
    {
        $this->container['local_variables'] = $local_variables;

        return $this;
    }

    /**
     * Gets business_key
     *
     * @return string|null
     */
    public function getBusinessKey()
    {
        return $this->container['business_key'];
    }

    /**
     * Sets business_key
     *
     * @param string|null $business_key A `String` value which enables the filtering of tasks based on process instance business key.
     *
     * @return $this
     */
    public function setBusinessKey($business_key)
    {
        $this->container['business_key'] = $business_key;

        return $this;
    }

    /**
     * Gets process_definition_id
     *
     * @return string|null
     */
    public function getProcessDefinitionId()
    {
        return $this->container['process_definition_id'];
    }

    /**
     * Sets process_definition_id
     *
     * @param string|null $process_definition_id Filter tasks based on process definition id.
     *
     * @return $this
     */
    public function setProcessDefinitionId($process_definition_id)
    {
        $this->container['process_definition_id'] = $process_definition_id;

        return $this;
    }

    /**
     * Gets process_definition_id_in
     *
     * @return string[]|null
     */
    public function getProcessDefinitionIdIn()
    {
        return $this->container['process_definition_id_in'];
    }

    /**
     * Sets process_definition_id_in
     *
     * @param string[]|null $process_definition_id_in Filter tasks based on process definition ids.
     *
     * @return $this
     */
    public function setProcessDefinitionIdIn($process_definition_id_in)
    {
        $this->container['process_definition_id_in'] = $process_definition_id_in;

        return $this;
    }

    /**
     * Gets process_definition_key
     *
     * @return string|null
     */
    public function getProcessDefinitionKey()
    {
        return $this->container['process_definition_key'];
    }

    /**
     * Sets process_definition_key
     *
     * @param string|null $process_definition_key Filter tasks based on process definition key.
     *
     * @return $this
     */
    public function setProcessDefinitionKey($process_definition_key)
    {
        $this->container['process_definition_key'] = $process_definition_key;

        return $this;
    }

    /**
     * Gets process_definition_key_in
     *
     * @return string[]|null
     */
    public function getProcessDefinitionKeyIn()
    {
        return $this->container['process_definition_key_in'];
    }

    /**
     * Sets process_definition_key_in
     *
     * @param string[]|null $process_definition_key_in Filter tasks based on process definition keys.
     *
     * @return $this
     */
    public function setProcessDefinitionKeyIn($process_definition_key_in)
    {
        $this->container['process_definition_key_in'] = $process_definition_key_in;

        return $this;
    }

    /**
     * Gets process_definition_version_tag
     *
     * @return string|null
     */
    public function getProcessDefinitionVersionTag()
    {
        return $this->container['process_definition_version_tag'];
    }

    /**
     * Sets process_definition_version_tag
     *
     * @param string|null $process_definition_version_tag Filter tasks based on process definition version tag.
     *
     * @return $this
     */
    public function setProcessDefinitionVersionTag($process_definition_version_tag)
    {
        $this->container['process_definition_version_tag'] = $process_definition_version_tag;

        return $this;
    }

    /**
     * Gets without_tenant_id
     *
     * @return bool|null
     */
    public function getWithoutTenantId()
    {
        return $this->container['without_tenant_id'];
    }

    /**
     * Sets without_tenant_id
     *
     * @param bool|null $without_tenant_id Filter tasks without tenant id.
     *
     * @return $this
     */
    public function setWithoutTenantId($without_tenant_id)
    {
        $this->container['without_tenant_id'] = $without_tenant_id;

        return $this;
    }

    /**
     * Gets tenant_id_in
     *
     * @return string[]|null
     */
    public function getTenantIdIn()
    {
        return $this->container['tenant_id_in'];
    }

    /**
     * Sets tenant_id_in
     *
     * @param string[]|null $tenant_id_in Filter tasks based on tenant ids.
     *
     * @return $this
     */
    public function setTenantIdIn($tenant_id_in)
    {
        $this->container['tenant_id_in'] = $tenant_id_in;

        return $this;
    }

    /**
     * Gets process_variables
     *
     * @return map[string,object]|null
     */
    public function getProcessVariables()
    {
        return $this->container['process_variables'];
    }

    /**
     * Sets process_variables
     *
     * @param map[string,object]|null $process_variables A `JSON` object used for filtering tasks based on process instance variable values. A property name of the object represents a process variable name, while the property value represents the process variable value to filter tasks by.
     *
     * @return $this
     */
    public function setProcessVariables($process_variables)
    {
        $this->container['process_variables'] = $process_variables;

        return $this;
    }

    /**
     * Gets deserialize_values
     *
     * @return bool|null
     */
    public function getDeserializeValues()
    {
        return $this->container['deserialize_values'];
    }

    /**
     * Sets deserialize_values
     *
     * @param bool|null $deserialize_values Determines whether serializable variable values (typically variables that store custom Java objects) should be deserialized on server side (default `false`).  If set to `true`, a serializable variable will be deserialized on server side and transformed to JSON using [Jackson's](https://github.com/FasterXML/jackson) POJO/bean property introspection feature. Note that this requires the Java classes of the variable value to be on the REST API's classpath.  If set to `false`, a serializable variable will be returned in its serialized format. For example, a variable that is serialized as XML will be returned as a JSON string containing XML.
     *
     * @return $this
     */
    public function setDeserializeValues($deserialize_values)
    {
        $this->container['deserialize_values'] = $deserialize_values;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


