<?php
/**
 * MultiFormDeploymentDto
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  StrehleDe\CamundaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace StrehleDe\CamundaClient\Model;

use \ArrayAccess;
use \StrehleDe\CamundaClient\ObjectSerializer;

/**
 * MultiFormDeploymentDto Class Doc Comment
 *
 * @category Class
 * @package  StrehleDe\CamundaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MultiFormDeploymentDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MultiFormDeploymentDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'tenant_id' => 'string',
        'deployment_source' => 'string',
        'deploy_changed_only' => 'bool',
        'enable_duplicate_filtering' => 'bool',
        'deployment_name' => 'string',
        'data' => '\SplFileObject'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'tenant_id' => null,
        'deployment_source' => null,
        'deploy_changed_only' => null,
        'enable_duplicate_filtering' => null,
        'deployment_name' => null,
        'data' => 'binary'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tenant_id' => 'tenant-id',
        'deployment_source' => 'deployment-source',
        'deploy_changed_only' => 'deploy-changed-only',
        'enable_duplicate_filtering' => 'enable-duplicate-filtering',
        'deployment_name' => 'deployment-name',
        'data' => 'data'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tenant_id' => 'setTenantId',
        'deployment_source' => 'setDeploymentSource',
        'deploy_changed_only' => 'setDeployChangedOnly',
        'enable_duplicate_filtering' => 'setEnableDuplicateFiltering',
        'deployment_name' => 'setDeploymentName',
        'data' => 'setData'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tenant_id' => 'getTenantId',
        'deployment_source' => 'getDeploymentSource',
        'deploy_changed_only' => 'getDeployChangedOnly',
        'enable_duplicate_filtering' => 'getEnableDuplicateFiltering',
        'deployment_name' => 'getDeploymentName',
        'data' => 'getData'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['tenant_id'] = isset($data['tenant_id']) ? $data['tenant_id'] : null;
        $this->container['deployment_source'] = isset($data['deployment_source']) ? $data['deployment_source'] : null;
        $this->container['deploy_changed_only'] = isset($data['deploy_changed_only']) ? $data['deploy_changed_only'] : false;
        $this->container['enable_duplicate_filtering'] = isset($data['enable_duplicate_filtering']) ? $data['enable_duplicate_filtering'] : false;
        $this->container['deployment_name'] = isset($data['deployment_name']) ? $data['deployment_name'] : null;
        $this->container['data'] = isset($data['data']) ? $data['data'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tenant_id
     *
     * @return string|null
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param string|null $tenant_id The tenant id for the deployment to be created.
     *
     * @return $this
     */
    public function setTenantId($tenant_id)
    {
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets deployment_source
     *
     * @return string|null
     */
    public function getDeploymentSource()
    {
        return $this->container['deployment_source'];
    }

    /**
     * Sets deployment_source
     *
     * @param string|null $deployment_source The source for the deployment to be created.
     *
     * @return $this
     */
    public function setDeploymentSource($deployment_source)
    {
        $this->container['deployment_source'] = $deployment_source;

        return $this;
    }

    /**
     * Gets deploy_changed_only
     *
     * @return bool|null
     */
    public function getDeployChangedOnly()
    {
        return $this->container['deploy_changed_only'];
    }

    /**
     * Sets deploy_changed_only
     *
     * @param bool|null $deploy_changed_only A flag indicating whether the process engine should perform duplicate checking on a per-resource basis. If set to true, only those resources that have actually changed are deployed. Checks are made against resources included previous deployments of the same name and only against the latest versions of those resources. If set to true, the option enable-duplicate-filtering is overridden and set to true.
     *
     * @return $this
     */
    public function setDeployChangedOnly($deploy_changed_only)
    {
        $this->container['deploy_changed_only'] = $deploy_changed_only;

        return $this;
    }

    /**
     * Gets enable_duplicate_filtering
     *
     * @return bool|null
     */
    public function getEnableDuplicateFiltering()
    {
        return $this->container['enable_duplicate_filtering'];
    }

    /**
     * Sets enable_duplicate_filtering
     *
     * @param bool|null $enable_duplicate_filtering A flag indicating whether the process engine should perform duplicate checking for the deployment or not. This allows you to check if a deployment with the same name and the same resouces already exists and if true, not create a new deployment but instead return the existing deployment. The default value is false.
     *
     * @return $this
     */
    public function setEnableDuplicateFiltering($enable_duplicate_filtering)
    {
        $this->container['enable_duplicate_filtering'] = $enable_duplicate_filtering;

        return $this;
    }

    /**
     * Gets deployment_name
     *
     * @return string|null
     */
    public function getDeploymentName()
    {
        return $this->container['deployment_name'];
    }

    /**
     * Sets deployment_name
     *
     * @param string|null $deployment_name The name for the deployment to be created.
     *
     * @return $this
     */
    public function setDeploymentName($deployment_name)
    {
        $this->container['deployment_name'] = $deployment_name;

        return $this;
    }

    /**
     * Gets data
     *
     * @return \SplFileObject|null
     */
    public function getData()
    {
        return $this->container['data'];
    }

    /**
     * Sets data
     *
     * @param \SplFileObject|null $data The binary data to create the deployment resource. It is possible to have more than one form part with different form part names for the binary data to create a deployment.
     *
     * @return $this
     */
    public function setData($data)
    {
        $this->container['data'] = $data;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


