<?php
/**
 * ProcessDefinitionDto
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  StrehleDe\CamundaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.13.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace StrehleDe\CamundaClient\Model;

use \ArrayAccess;
use \StrehleDe\CamundaClient\ObjectSerializer;

/**
 * ProcessDefinitionDto Class Doc Comment
 *
 * @category Class
 * @package  StrehleDe\CamundaClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProcessDefinitionDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProcessDefinitionDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'key' => 'string',
        'category' => 'string',
        'description' => 'string',
        'name' => 'string',
        'version' => 'int',
        'resource' => 'string',
        'deployment_id' => 'string',
        'diagram' => 'string',
        'suspended' => 'bool',
        'tenant_id' => 'string',
        'version_tag' => 'string',
        'history_time_to_live' => 'int',
        'startable_in_tasklist' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'id' => null,
        'key' => null,
        'category' => null,
        'description' => null,
        'name' => null,
        'version' => 'int32',
        'resource' => null,
        'deployment_id' => null,
        'diagram' => null,
        'suspended' => null,
        'tenant_id' => null,
        'version_tag' => null,
        'history_time_to_live' => 'int32',
        'startable_in_tasklist' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'key' => 'key',
        'category' => 'category',
        'description' => 'description',
        'name' => 'name',
        'version' => 'version',
        'resource' => 'resource',
        'deployment_id' => 'deploymentId',
        'diagram' => 'diagram',
        'suspended' => 'suspended',
        'tenant_id' => 'tenantId',
        'version_tag' => 'versionTag',
        'history_time_to_live' => 'historyTimeToLive',
        'startable_in_tasklist' => 'startableInTasklist'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'key' => 'setKey',
        'category' => 'setCategory',
        'description' => 'setDescription',
        'name' => 'setName',
        'version' => 'setVersion',
        'resource' => 'setResource',
        'deployment_id' => 'setDeploymentId',
        'diagram' => 'setDiagram',
        'suspended' => 'setSuspended',
        'tenant_id' => 'setTenantId',
        'version_tag' => 'setVersionTag',
        'history_time_to_live' => 'setHistoryTimeToLive',
        'startable_in_tasklist' => 'setStartableInTasklist'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'key' => 'getKey',
        'category' => 'getCategory',
        'description' => 'getDescription',
        'name' => 'getName',
        'version' => 'getVersion',
        'resource' => 'getResource',
        'deployment_id' => 'getDeploymentId',
        'diagram' => 'getDiagram',
        'suspended' => 'getSuspended',
        'tenant_id' => 'getTenantId',
        'version_tag' => 'getVersionTag',
        'history_time_to_live' => 'getHistoryTimeToLive',
        'startable_in_tasklist' => 'getStartableInTasklist'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['key'] = isset($data['key']) ? $data['key'] : null;
        $this->container['category'] = isset($data['category']) ? $data['category'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['version'] = isset($data['version']) ? $data['version'] : null;
        $this->container['resource'] = isset($data['resource']) ? $data['resource'] : null;
        $this->container['deployment_id'] = isset($data['deployment_id']) ? $data['deployment_id'] : null;
        $this->container['diagram'] = isset($data['diagram']) ? $data['diagram'] : null;
        $this->container['suspended'] = isset($data['suspended']) ? $data['suspended'] : null;
        $this->container['tenant_id'] = isset($data['tenant_id']) ? $data['tenant_id'] : null;
        $this->container['version_tag'] = isset($data['version_tag']) ? $data['version_tag'] : null;
        $this->container['history_time_to_live'] = isset($data['history_time_to_live']) ? $data['history_time_to_live'] : null;
        $this->container['startable_in_tasklist'] = isset($data['startable_in_tasklist']) ? $data['startable_in_tasklist'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['history_time_to_live']) && ($this->container['history_time_to_live'] < 0)) {
            $invalidProperties[] = "invalid value for 'history_time_to_live', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id The id of the process definition
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets key
     *
     * @return string|null
     */
    public function getKey()
    {
        return $this->container['key'];
    }

    /**
     * Sets key
     *
     * @param string|null $key The key of the process definition, i.e., the id of the BPMN 2.0 XML process definition.
     *
     * @return $this
     */
    public function setKey($key)
    {
        $this->container['key'] = $key;

        return $this;
    }

    /**
     * Gets category
     *
     * @return string|null
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param string|null $category The category of the process definition.
     *
     * @return $this
     */
    public function setCategory($category)
    {
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description The description of the process definition.
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name The name of the process definition.
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets version
     *
     * @return int|null
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param int|null $version The version of the process definition that the engine assigned to it.
     *
     * @return $this
     */
    public function setVersion($version)
    {
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets resource
     *
     * @return string|null
     */
    public function getResource()
    {
        return $this->container['resource'];
    }

    /**
     * Sets resource
     *
     * @param string|null $resource The file name of the process definition.
     *
     * @return $this
     */
    public function setResource($resource)
    {
        $this->container['resource'] = $resource;

        return $this;
    }

    /**
     * Gets deployment_id
     *
     * @return string|null
     */
    public function getDeploymentId()
    {
        return $this->container['deployment_id'];
    }

    /**
     * Sets deployment_id
     *
     * @param string|null $deployment_id The deployment id of the process definition.
     *
     * @return $this
     */
    public function setDeploymentId($deployment_id)
    {
        $this->container['deployment_id'] = $deployment_id;

        return $this;
    }

    /**
     * Gets diagram
     *
     * @return string|null
     */
    public function getDiagram()
    {
        return $this->container['diagram'];
    }

    /**
     * Sets diagram
     *
     * @param string|null $diagram The file name of the process definition diagram, if it exists.
     *
     * @return $this
     */
    public function setDiagram($diagram)
    {
        $this->container['diagram'] = $diagram;

        return $this;
    }

    /**
     * Gets suspended
     *
     * @return bool|null
     */
    public function getSuspended()
    {
        return $this->container['suspended'];
    }

    /**
     * Sets suspended
     *
     * @param bool|null $suspended A flag indicating whether the definition is suspended or not.
     *
     * @return $this
     */
    public function setSuspended($suspended)
    {
        $this->container['suspended'] = $suspended;

        return $this;
    }

    /**
     * Gets tenant_id
     *
     * @return string|null
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param string|null $tenant_id The tenant id of the process definition.
     *
     * @return $this
     */
    public function setTenantId($tenant_id)
    {
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets version_tag
     *
     * @return string|null
     */
    public function getVersionTag()
    {
        return $this->container['version_tag'];
    }

    /**
     * Sets version_tag
     *
     * @param string|null $version_tag The version tag of the process definition.
     *
     * @return $this
     */
    public function setVersionTag($version_tag)
    {
        $this->container['version_tag'] = $version_tag;

        return $this;
    }

    /**
     * Gets history_time_to_live
     *
     * @return int|null
     */
    public function getHistoryTimeToLive()
    {
        return $this->container['history_time_to_live'];
    }

    /**
     * Sets history_time_to_live
     *
     * @param int|null $history_time_to_live History time to live value of the process definition. Is used within [History cleanup](https://docs.camunda.org/manual/7.13/user-guide/process-engine/history/#history-cleanup).
     *
     * @return $this
     */
    public function setHistoryTimeToLive($history_time_to_live)
    {

        if (!is_null($history_time_to_live) && ($history_time_to_live < 0)) {
            throw new \InvalidArgumentException('invalid value for $history_time_to_live when calling ProcessDefinitionDto., must be bigger than or equal to 0.');
        }

        $this->container['history_time_to_live'] = $history_time_to_live;

        return $this;
    }

    /**
     * Gets startable_in_tasklist
     *
     * @return bool|null
     */
    public function getStartableInTasklist()
    {
        return $this->container['startable_in_tasklist'];
    }

    /**
     * Sets startable_in_tasklist
     *
     * @param bool|null $startable_in_tasklist A flag indicating whether the process definition is startable in Tasklist or not.
     *
     * @return $this
     */
    public function setStartableInTasklist($startable_in_tasklist)
    {
        $this->container['startable_in_tasklist'] = $startable_in_tasklist;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


